version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Mapea el puerto 8080 en tu máquina al puerto 80 del contenedor
    volumes:
      - .:/var/www/html  # Mapea los archivos del proyecto al contenedor
    environment:
      - PHP_ENV=production
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: botica_db
    volumes:
      - db_data:/var/lib/mysql  # Volumen persistente para la base de datos

volumes:
  db_data:
