version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=botica-bienestar-devops.onrender.com
    networks:
      - default

networks:
  default:
    driver: bridge
